apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
configMapGenerator:
  - name: coredns
    files:
      - Corefile
generatorOptions:
  disableNameSuffixHash: true
resources:
  - service.yaml
