apiVersion: v1
kind: Service
metadata:
  name: external-dns
spec:
  loadBalancerIP: 192.168.178.250
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
