plan:
    tofu -chdir=nodes plan
    tofu -chdir=cluster plan

apply:
    tofu -chdir=nodes apply
    tofu -chdir=cluster apply

get-kubeconfig:
    tofu -chdir=nodes output -raw kubeconfig > ~/.kube/config

get-talosconfig:
    mkdir -p ~/.config/talos && tofu -chdir=nodes output -raw talosconfig > ~/.talos/config
